---
version: 1

provider: "sqlite3"

allow_unknown_extensions: false
plugin_enabled: true
debug: false

check_updates: true

language: "eng"

block_commands: true
prevent_place: true
prevent_break: true
prevent_gamemode_change: true

auto_start: true
start_countdown: 10

KingTextParticles: true

nametag_enabled: true
nametag_format: "{RED}[ {GREEN}KING {RED}]"
...