---
version: 1

provider: "sqlite3"

plugin_enabled: true
debug: false

check_updates: true

language: "eng"

block_commands: true
prevent_place: true
prevent_break: true
prevent_gamemode_change: true

start_countdown: 10

KingTextParticles: true

nametag_enabled: true
nametag_format: "{RED}[ {GREEN}KING {RED}]"

#Todo add all messages before Beta2 release.
#Possibly the broadcast as well.
...