---
version: 1

provider: "sqlite3"

debug: false

show_updates: true
check_updates: true
update_check_url: "https://raw.githubusercontent.com/jackthehack21/koth/master/github/updates.json"

block_commands: true
prevent_place: true
prevent_break: true
prevent_gamemode_change: true
keep_inventory: true

auto_start: true
start_countdown: 10

KingTextParticles: true

nametag_enabled: true
nametag_format: "{RED}[ {GREEN}KING {RED}]"
...