---
version: 0

plugin_enabled: true
debug: false

check_updates: true

language: "eng"

KingTextParticles: true

nametag_enabled: true
nametag_format: "{RED}[ {GREEN}KING {RED}]"

start_countdown: 10
...